CREATE TABLE Admin
(
  AdmID INT(5) NOT NULL AUTO_INCREMENT,
  AdmName VARCHAR(50) NOT NULL,
  AdmPhone CHAR(10) NOT NULL,
  AdmEmail VARCHAR(50) NOT NULL,
  AdmPassword VARCHAR(50) NOT NULL,
  PRIMARY KEY (AdmID),
  UNIQUE (AdmEmail)
);

CREATE TABLE Owner
(
  OwnID INT(5) NOT NULL AUTO_INCREMENT,
  OwnName VARCHAR(50) NOT NULL,
  OwnPhone CHAR(10) NOT NULL,
  OwnEmail VARCHAR(50) NOT NULL,
  OwnPassword VARCHAR(50) NOT NULL,
  OwnPic BLOB NOT NULL,
  OwnActive CHAR(1) NOT NULL,
  OwnLat float(10,6) NOT NULL,
  OwnLng float(10,6) NOT NULL,
  AdmID INT(5) NOT NULL,
  PRIMARY KEY (OwnID),
  FOREIGN KEY (AdmID) REFERENCES Admin(AdmID)
);

CREATE TABLE Branch
(
  BName VARCHAR(50) NOT NULL,
  BPhone CHAR(10) NOT NULL,
  BID INT(5) NOT NULL AUTO_INCREMENT,
  BActive CHAR(1) NOT NULL,
  BLat float(10,6) NOT NULL,
  Blng float(10,6) NOT NULL,
  OwnID INT(5) NOT NULL,
  PRIMARY KEY (BID),
  FOREIGN KEY (OwnID) REFERENCES Owner(OwnID)
);

CREATE TABLE Employee
(
  EmpID INT(5) NOT NULL AUTO_INCREMENT,
  EmpName VARCHAR(50) NOT NULL,
  EmpPhone CHAR(10) NOT NULL,
  EmpActive CHAR(1) NOT NULL,
  EmpPic BLOB NOT NULL,
  BID INT(5) NOT NULL,
  AdmID INT(5) NOT NULL,
  PRIMARY KEY (EmpID),
  FOREIGN KEY (BID) REFERENCES Branch(BID),
  FOREIGN KEY (AdmID) REFERENCES Admin(AdmID)
);